### ISSUE TITLE
ERROR `/{{ photo.images.thumbnail.url }}' not found.

### ISSUE THREAD

**Issue by anguyend** [benbarber/jekyll-instagram#7] opened 2022-01-04 17:38 UTC
Hi @benbarber, 

I'm trying to implement your plugin and am getting this error message when I run the application,

ERROR `/{{ photo.images.thumbnail.url }}' not found.

**Comment by benbarber** [comment] 2022-01-06 10:51
Hi @anguyend, I'm not sure on the cause of that error from the information given. 

Can you create an example repo reproducing the error so I can take a look?

**Comment by benbarber** [comment] 2022-01-07 11:25
Hi @anguyend,

I have now updated the plugin to work with the latest Instagram API. Please try the latest version of the plugin along with the updated template code thats in the Readme and let me know if that solves your issues.

**Comment by benbarber** [comment] 2022-02-24 14:01
Closing this issue as I assume its now resolved.

**Closed as completed by benbarber** 2022-02-24 14:01 UTC
